config/routes.rb
IssuesTimetracker::Application.routes.draw do

  devise_for :users

  resources :projects
  resources :issues do
    match 'track/start' => 'time_trackers#start'
    match 'track/stop' => 'time_trackers#stop'
    match 'track/pause' => 'time_trackers#pause'
    match 'track/resume' => 'time_trackers#resume'
  end

  root :to => 'welcome#index'
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessor :creator
  attr_accessible :description, :project_id, :title

  belongs_to :project
  has_one :time_tracker, :dependent => :destroy

  validates :title, :presence => true
  validate :manage_only_own_projects

  def time_spent_str
    total = spent_time + (time_tracker.try(:hours_spent) || 0)
    hours = total.to_i
    minutes = ((total - hours) * 60).to_i
    hours.to_s + ':' + minutes.to_s.rjust(2, '0')
  end

  protected

  def manage_only_own_projects
    errors.add(:base, 'You can manage only own projects') if (self.creator != Project.find(self.project_id).user)
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessor :current_user
  attr_accessible :description, :title

  belongs_to :user
  has_many :issues, :dependent => :destroy

  validates :title, :presence => true

end

app/models/time_tracker.rb
class TimeTracker < ActiveRecord::Base
  attr_accessible :issue_id, :started_on, :as => :system
  belongs_to :issue
  validates_presence_of :issue_id

  def initialize(arguments = nil, options = {})
    super(arguments, options)
    self.started_at = Time.now
  end

  def hours_spent
    ((Time.now.to_i - started_at.to_i) / 3600.0).to_f
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :projects
  has_many :issues, :through => :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
  def load_general_data
    @my_projects = current_user.projects if user_signed_in?
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :load_general_data, :only => [:show, :new, :edit, :create]
  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = current_user.issues.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new(:project_id => params[:project_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = current_user.issues.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])
    @issue.creator = current_user
    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = current_user.issues.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :load_general_data, :only => [:show, :new, :edit, :create]
  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = current_user.projects.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/time_trackers_controller.rb
class TimeTrackersController < ApplicationController
  def start
    TimeTracker.create({:issue_id => issue.id}, :as => :system)
    respond_to do |format|
      format.js { render :partial => 'actions', :locals => {:issue => issue} }
    end
  end

  def stop
    @time_tracker = issue.time_tracker
    issue.update_column :spent_time, (@time_tracker.hours_spent + issue.spent_time).round(2)
    @time_tracker.destroy
    respond_to do |format|
      format.js { render :partial => 'actions', :locals => {:issue => issue} }
    end
  end

  protected

  def issue
    current_user.issues.find(params[:issue_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :load_general_data
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/issues/_actions.html.erb
<% if issue.time_tracker %>
    <%= link_to 'stop', issue_track_stop_path(issue.id), :remote => true %>
<% else %>
    <%= link_to 'start', issue_track_start_path(issue.id), :remote => true %>
<% end %>

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">&#215;</a>
      <h4><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h4>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <%= f.hidden_field :project_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', :back %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @issue.title %>
</h3>
<p>
  <%= @issue.description %>
</p>
<div id="issue-<%= @issue.id %>">

<div>
  timer:
  <span class="actions">
    <%= render :partial => 'issues/actions', :locals => {:issue => @issue} %>
  </span>
</div>
  already spent time <span class="spent-time"><%= @issue.time_spent_str %></span>
</div>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Destroy', @issue, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "issues_timetracker" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "issues_timetracker" %>">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<div id="main" role="main">
  <div class="container">
    <div class="hero-unit">
      <h1>The timetracker</h1>
    </div>
    <div class="content">
      <div class="row">

        <div class="span2">
          <% if user_signed_in? %>
            <%= render :partial => "projects/my", :locals => { :projects => @my_projects} unless @my_projects.nil? %>
          <% end %>
        </div>
        <div class="span10">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">&#215;</a>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_index.html.erb
<table>
  <tr>
    <th>Projects</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.title, project %></td>
  </tr>
<% end %>
</table>
<br />

app/views/projects/_my.erb
    <ul class="nav nav-pills nav-stacked">
    <li class="nav-header">My projects</li>
      <% unless projects.empty? %>
        <% projects.each do |project|%>
          <li>
            <%= link_to project.title, project %>
          </li>
        <% end %>
      <% end %>
      <li>
      <%= link_to '+ Project', new_project_path, :class => "muted" %>
      </li>
    </ul>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |

app/views/projects/new.html.erb
<h1>New project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h4>
  <%= @project.title %> <sup class="small"><%= link_to 'Edit', edit_project_path(@project) %> | <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Destroy project and all related issues?' } %></sup>
</h4>
<p>
  <%= @project.description %>
</p>
<br>
<h5>
  Issues:<sup class="small"> <%= link_to 'Add issue', new_issue_path(:project_id => @project.id) %> </sup>
</h5>
<% unless @project.issues.empty? %>
    <table class="table table-striped">
      <tr>
            <th>
              Title
            </th>
            <th>
              Timer
            </th>
            <th>
              Time spent
            </th>
          </tr>
      <% @project.issues.order(:id).each do |issue| %>
          <tr id="issue-<%= issue.id %>">
            <td><%= link_to issue.title, issue_path(issue) %></td>
            <td class="actions">
              <%= render :partial => 'issues/actions', :locals => {:issue => issue} %>
            </td>
            <td class="spent-time">
              <%= issue.time_spent_str %>
            </td>
          </tr>

      <% end %>
    </table>
<% end %>

app/views/time_trackers/_actions.js.erb
var issue = $('#issue-<%= issue.id %>')
$('.actions', issue).html('<%= j(render :partial => "issues/actions", :locals => {:issue => issue}) %>');
$('.spent-time', issue).html('<%= issue.time_spent_str %>');